{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "the-boss-app.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "the-boss-app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "the-boss-app.selectorLabels" . | nindent 6 }}
{{- end }}
